#!/bin/bash

set -x

sudo mkdir /etc/ssl/nginx
sudo cp ../license/nginx-repo.crt /etc/ssl/nginx/
sudo cp ../license/nginx-repo.key /etc/ssl/nginx/

sudo apt-get -y update

#Install prerequisites
sudo apt-get -y install apt-transport-https lsb-release ca-certificates dirmngr

# Install NGINX signing key
sudo wget https://nginx.org/keys/nginx_signing.key
sudo apt-key add nginx_signing.key
printf "deb https://pkgs.nginx.com/nms/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nms.list
printf "deb https://pkgs.nginx.com/plus/ubuntu `lsb_release -cs` nginx-plus\n" | sudo tee /etc/apt/sources.list.d/nginx-plus.list
sudo wget -q -O /etc/apt/apt.conf.d/90pkgs-nginx https://cs.nginx.com/static/files/90pkgs-nginx

# Install ClickHouse signing key
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 8919F6BD2B48D754
echo "deb https://packages.clickhouse.com/deb stable main" | sudo tee \
    /etc/apt/sources.list.d/clickhouse.list

# Update repos to incl. NGINX/ClickHouse
sudo apt-get -y update

# Install NGINX Plus and ClickHouse
DEBIAN_FRONTEND=noninteractive sudo apt-get -y install -y nginx-plus clickhouse-server clickhouse-client
sudo service clickhouse-server start

# Install NIM
sudo apt-get install -y nms-instance-manager
sudo systemctl start clickhouse-server
sudo systemctl restart nginx
sudo systemctl enable nms-core
sudo systemctl enable nms-dpm
sudo systemctl enable nms-ingestion
sudo systemctl enable nms
sudo systemctl start nms
